<?php

return [

    'kiss' => [
        'apiurl' => env('APIURL_KISS', 'http://api.918kiss.com:9991/'),
        'apiurl2' => env('APIURL2', 'http://api.918kiss.com:9919/'),
        'agent' => env('AGENT_KISS', 'thokaa02aa'),
        'login' => env('LOGIN_KISS', 'thokaa02aa'),
        'auth' => env('AUTH_KISS', 'bqtkbXQHSYcZnkcTwJdS'),
        'secretkey' => env('SECRETKEY_KISS', 'z9Ry47XE2K862676355j'),
    ],
    'pussy' => [
        'apiurl' => env('APIURL_PUSSY', 'http://api.pussy888.com/'),
        'apiurl2' => env('APIURL2', 'http://api2.pussy888.com/'),
        'agent' => env('AGENT_PUSSY', 'THOKLY02A'),
        'login' => env('LOGIN_PUSSY', 'THOKLY02A'),
        'auth' => env('AUTH_PUSSY', 'QTXaegFNKAZGMAGccjxS'),
        'secretkey' => env('SECRETKEY_PUSSY', '74aFgrC8T2yWQUM725ey'),
    ],
    'jokernew' => [
        'apiurl' => env('APIURL_JOKER', 'https://joker.hibizsoft.com/joker_api/'),
        'apiurl2' => env('APIURL2', 'http://api688.com:80/'),
        'agent' => env('AGENT', 'dumbovip'),
        'login' => env('APPID_JOKER', 'dumbovip'),
        'auth' => env('AUTH', 'n3g1kNb0oDY5Olq5MFdj'),
        'secretkey' => env('SECRETKEY_JOKER', '13nquaXHhENISQ1vUKJRcQ=='),
    ],
    'joker' => [
        'apiurl' => env('APIURL_JOKER', 'http://api688.com:80/'),
        'apiurl2' => env('APIURL2', 'http://api688.com:80/'),
        'agent' => env('AGENT', 'AKEH02A'),
        'login' => env('APPID_JOKER', 'AKEH02A'),
        'auth' => env('AUTH', 'gt8w36cyh3gur'),
        'secretkey' => env('SECRETKEY_JOKER', 'gt8w36cyh3gur'),
    ],
    'slotxo' => [
        'apiurl' => env('APIURL_SLOTXO', 'http://api688.com:80/'),
        'apiurl2' => env('APIURL2', 'http://api688.com:80/'),
        'agent' => env('AGENT', ''),
        'login' => env('APPID_SLOTXO', 'LUYFF02A'),
        'auth' => env('AUTH', ''),
        'secretkey' => env('SECRETKEY_SLOTXO', 'khtn8f8docifq'),
    ],
    'slotx' => [
        'apiurl' => env('APIURL_SLOTX', 'http://api688.com:80/'),
        'apiurl2' => env('APIURL2', 'http://api688.com:80/'),
        'agent' => env('AGENT', ''),
        'login' => env('APPID_SLOTX', 'SVV001'),
        'auth' => env('AUTH', ''),
        'secretkey' => env('SECRETKEY_SLOTX', 'rtxtjne9myhnr'),
    ],
    'live22' => [
        'apiurl' => env('APIURL_LIVE22', 'https://topup-casino.api-hub.com:22222/external/sit22/'),
        'apiurl2' => env('APIURL2', 'https://topup-casino.api-hub.com:22222/external/sit22/'),
        'agent' => env('AGENT_LIVE22', 'thsv77'),
        'agent_pass' => env('AGENT_PASS_LIVE22', 'Aa321654'),
        'login' => env('LOGIN', ''),
        'auth' => env('AUTH', ''),
        'secretkey' => env('SECRETKEY', ''),
    ],
    'nxcasino' => [
        'apiurl' => env('APIURL', 'http://op01.nxcasino.com/api/service/'),
        'apiurl2' => env('APIURL2', 'http://op01.nxcasino.com/api/service/'),
        'agent' => env('AGENT', ''),
        'agent_pass' => env('AGENT_PASS', ''),
        'login' => env('LOGIN', ''),
        'auth' => env('AUTH', ''),
        'secretkey' => env('SECRETKEY', ''),
    ],
    'avenger' => [
        'apiurl' => env('APIURL', 'http://thedevpers.com/avenger/'),
        'apiurl2' => env('APIURL2', 'http://thedevpers.com/avenger/'),
        'agent' => env('AGENT', 'AVGA03A'),
        'agent_pass' => env('AGENT_PASS', ''),
        'login' => env('LOGIN', 'AVGA03A'),
        'auth' => env('AUTH', ''),
        'secretkey' => env('SECRETKEY', ''),
    ],
    'gott7' => [
        'apiurl' => env('APIURL', 'https://www.gott7.com/api/service/'),
        'apiurl2' => env('APIURL2', 'https://www.gott7.com/api/service/'),
        'agent' => env('AGENT', '26'),
        'agent_pass' => env('AGENT_PASS', ''),
        'login' => env('LOGIN', ''),
        'auth' => env('AUTH', ''),
        'secretkey' => env('SECRETKEY', 'da39a3ee5e6b4b0d3255bfef95601890afd80709'),
    ],
    'dreamtech' => [
        'apiurl' => env('APIURL_DREAMTECH', 'http://agency.dreamtech888.com/api_service/'),
        'apiurl2' => env('APIURL2', 'http://agency.dreamtech888.com/api_service/'),
        'agent' => env('AGENT_DREAMTECH', 'svv001'),
        'agent_pass' => env('AGENT_PASS', ''),
        'login' => env('LOGIN', ''),
        'auth' => env('AUTH', ''),
        'secretkey' => env('API_KEYDT', ''),
        'appid' => env('APP_ID', 26),
        'passkey' => env('PASSKEY_DREAMTECH', 'd6ad6d45-c67e-4cc9-88a8-3e36bb84e1e4'),
        'apikey' => env('API_KEY', ''),
        'apiuser' => env('API_USR', 'DTOPSITE-PROD'),
    ],
    'epic' => [
        'apiurl' => env('APIURL_EPIC', 'https://epicwinapi.com/tapi/'),
        'apiurl2' => env('APIURL2', 'https://epicwinapi.com/tapi/'),
        'agent' => env('AGENT_EPIC', 'Thad02'),
        'agent_pass' => env('AGENT_PASS_EPIC', 'Aa159623')
    ],
    'kaya' => [
        'apiurl' => env('APIURL_KAYA', 'http://apiservice.da31889.com/v1/'),
        'apiurl2' => env('APIURL2', 'http://apiservice.da31889.com/v1/'),
        'agent' => env('AGENT_KAYA', 'svv001'),
        'secretkey' => env('SECRETKEY_KAYA', 'oC5kA4VO6NZzghtR'),
        'passkey' => env('PASSKEY_KAYA', 'ZjmQHbMfJLAdpUVt8lc3XnPEhIY17Nr5')
    ],
    'pgslot' => [
        'apiurl' => env('APIURL_PGSLOT', 'https://api-prod.pgslot-api.com/'),
        'agenturl' => env('APIURL2', 'https://ag-dev.pgslot.cc/'),
        'agent' => env('AGENT_PGSLOT', 'pg7777'),
        'secretkey' => env('SECRETKEY_PGSLOT', '5d12e02b0e6ff1a55587e99c0e06aa8d')
    ],
    '100plus' => [
        'apiurl' => env('APIURL_100PLUS', 'https://api.100plus.me/b/'),
        'agenturl' => env('APIURL2', 'https://ag-dev.pgslot.cc/'),
        'agent' => env('AGENT_100PLUS', 'THsv77vip'),
        'agent_pass' => env('AGENT_PASS_100PLUS', 'd032cdd7c5864480bcf925f749594e6f'),
        'secretkey' => env('SECRETKEY_100PLUS', 'A1asd4fhu4E45Gdmk')
    ],
];
