<?php

return [
    [
        'key' => 'line-oa',
        'name' => 'Line OA',
        'route' => 'admin.line-oa.chat',
        'sort' => 88,
        'icon-class' => 'fa-gamepad',
        'badge' => 0,
        'badge-color' => 'badge-primary',
        'status' => 1,
    ],
    [
        'key' => 'line-oa.chat',
        'name' => 'Line Chat',
        'route' => 'admin.line-oa.chat',
        'sort' => 1,
        'icon-class' => 'fa-gamepad',
        'badge' => 0,
        'badge-color' => 'badge-primary',
        'status' => 1,
    ],
    [
        'key' => 'line-oa.line_account',
        'name' => 'ตั้งค่า Line OA',
        'route' => 'admin.line_account.index',
        'sort' => 2,
        'icon-class' => 'fa-gamepad',
        'badge' => 0,
        'badge-color' => 'badge-primary',
        'status' => 1,
    ],
    [
        'key' => 'line-oa.line_template',
        'name' => 'ตั้งค่า ข้อความตอบกลับ',
        'route' => 'admin.line_template.index',
        'sort' => 3,
        'icon-class' => 'fa-gamepad',
        'badge' => 0,
        'badge-color' => 'badge-primary',
        'status' => 1,
    ],
    [
        'key' => 'topup',
        'name' => 'รายการ เงินเข้า',
        'route' => 'admin.topup.index',
        'sort' => 4,
        'icon-class' => 'fa-arrow-circle-left',
        'badge' => 0,
        'badge-color' => 'badge-warning',
        'status' => 0,
    ],
];
