<?php

return [
    [
        'key' => 'facebook-oa',
        'name' => 'Facebook OA',
        'route' => 'admin.facebook-oa.chat',
        'sort' => 89,
        'icon-class' => 'fa-gamepad',
        'badge' => 0,
        'badge-color' => 'badge-primary',
        'status' => 1,
    ],
    [
        'key' => 'facebook-oa.chat',
        'name' => 'Facebook Chat',
        'route' => 'admin.facebook-oa.chat',
        'sort' => 1,
        'icon-class' => 'fa-gamepad',
        'badge' => 0,
        'badge-color' => 'badge-primary',
        'status' => 1,
    ],
    [
        'key' => 'facebook-oa.facebook_account',
        'name' => 'ตั้งค่า Facebook OA',
        'route' => 'admin.facebook_account.index',
        'sort' => 2,
        'icon-class' => 'fa-gamepad',
        'badge' => 0,
        'badge-color' => 'badge-primary',
        'status' => 1,
    ],
    [
        'key' => 'facebook-oa.facebook_template',
        'name' => 'ตั้งค่า รูปแบบข้อความทั้งหมด',
        'route' => 'admin.facebook_template.index',
        'sort' => 3,
        'icon-class' => 'fa-gamepad',
        'badge' => 0,
        'badge-color' => 'badge-primary',
        'status' => 1,
    ],
    [
        'key' => 'facebook-oa.facebook_quick_reply',
        'name' => 'ตั้งค่า ข้อความส่งด่วน',
        'route' => 'admin.facebook_quick_reply.index',
        'sort' => 4,
        'icon-class' => 'fa-gamepad',
        'badge' => 0,
        'badge-color' => 'badge-primary',
        'status' => 1,
    ],
];
